name: Nightly Acceptance Tests

on:
  schedule:
    # Will run at 00:00 every day
    - cron: '0 0 * * *'

jobs:
  nightly:
    strategy:
      matrix:
        products:
          - Account
          - Baremetal
          - Instance
          - K8S
          - Lb
          - Object
          - Rdb
          - Registry
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Acceptance Tests
        run: go test -v ./... -timeout=1h -run TestAccScaleway${{ matrix.products }}*
        env:
          TF_LOG: DEBUG
          TF_ACC: 1
          SCW_DEBUG: 1
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
