name: Run tfproviderlint

on: [pull_request, push]

jobs:
  tfproviderlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: bflad/tfproviderlint-github-action@master
        with:
          args: ./...
